### PR TITLE
make srt more portable by building from source

### PR DESCRIPTION
**Pull request by ccbrown**
This deletes the precompiled libsrt binaries from the srt crate and adds a new crate: srt-sys.

This new crate includes a vendored copy of the latest srt release's source and compiles it using a custom build. This will enable us to compile for far more targets than the 3 we had precompiled binaries for.

I'll probably end up adding some Cargo features to control things like libstdc++ linkage, but this seems like a good start.

### CODE REVIEW

**Review by epingel2 — APPROVED** [review]
This is a good change and one which I have been meaning to bring up.

**Comment by lzuosym** [comment]
See some errors `cargo build`

```
av-rs/srt on  more-portable-srt [?] is 📦 v0.1.0 via 🦀 v1.62.0-nightly
❯ cargo build
   Compiling srt-sys v0.1.0 (/Users/leon/dev/av-rs/srt/srt-sys)
error: failed to run custom build command for `srt-sys v0.1.0 (/Users/leon/dev/av-rs/srt/srt-sys)`

Caused by:
  process didn't exit successfully: `/Users/leon/dev/av-rs/target/debug/build/srt-sys-6aadbf7642a1843b/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/leon/dev/av-rs/srt/srt-sys/vendor/srt-1.4.4" "-DENABLE_APPS=OFF" "-DENABLE_SHARED=OFF" "-DOPENSSL_INCLUDE_DIR=/Users/leon/dev/av-rs/srt/srt-sys/vendor/openssl/include" "-DOPENSSL_CRYPTO_LIBRARY=/Users/leon/dev/av-rs/srt/srt-sys/vendor/openssl/lib/macos-aarch64/libcrypto.a" "-DOPENSSL_SSL_LIBRARY=" "-DCMAKE_INSTALL_PREFIX=/Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin" "-DCMAKE_C_COMPILER=/usr/bin/clang" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin" "-DCMAKE_CXX_COMPILER=/usr/bin/clang++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin" "-DCMAKE_ASM_COMPILER=/usr/bin/clang" "-DCMAKE_BUILD_TYPE=Debug"
  -- The C compiler identification is AppleClang 13.1.6.13160021
  -- The CXX compiler identification is AppleClang 13.1.6.13160021
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: /usr/bin/clang
  -- Check for working C compiler: /usr/bin/clang - broken
  -- Configuring incomplete, errors occurred!
  See also "/Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeOutput.log".
  See also "/Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Error at /opt/homebrew/Cellar/cmake/3.23.1/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "/usr/bin/clang"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeTmp

      Run Build Command(s):/usr/bin/make -f Makefile cmTC_0daab/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_0daab.dir/build.make CMakeFiles/cmTC_0daab.dir/build
      Building C object CMakeFiles/cmTC_0daab.dir/testCCompiler.c.o
      /usr/bin/clang   -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -MD -MT CMakeFiles/cmTC_0daab.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_0daab.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_0daab.dir/testCCompiler.c.o -c /Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
      Linking C executable cmTC_0daab
      /opt/homebrew/Cellar/cmake/3.23.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0daab.dir/link.txt --verbose=1
      /usr/bin/clang  -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/llvm/lib /opt/homebrew/opt/ffmpeg@4/lib  CMakeFiles/cmTC_0daab.dir/testCCompiler.c.o -o cmTC_0daab
      ld: can't map file, errno=22 file '/opt/homebrew/opt/ffmpeg@4/lib' for architecture arm64
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      make[1]: *** [cmTC_0daab] Error 1
      make: *** [cmTC_0daab/fast] Error 2

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:24 (project)

  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /Users/leon/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  CMake Error at /opt/homebrew/Cellar/cmake/3.23.1/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "/usr/bin/clang"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeTmp
      
      Run Build Command(s):/usr/bin/make -f Makefile cmTC_9f6ba/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_9f6ba.dir/build.make CMakeFiles/cmTC_9f6ba.dir/build
      Building C object CMakeFiles/cmTC_9f6ba.dir/testCCompiler.c.o
      /usr/bin/clang   -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -MD -MT CMakeFiles/cmTC_9f6ba.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_9f6ba.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_9f6ba.dir/testCCompiler.c.o -c /Users/leon/dev/av-rs/target/debug/build/srt-sys-41470aeb6c4bede4/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
      Linking C executable cmTC_9f6ba
      /opt/homebrew/Cellar/cmake/3.23.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9f6ba.dir/link.txt --verbose=1
      /usr/bin/clang  -ffunction-sections -fdata-sections -fPIC --target=arm64-apple-darwin  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/llvm/lib /opt/homebrew/opt/ffmpeg@4/lib  CMakeFiles/cmTC_9f6ba.dir/testCCompiler.c.o -o cmTC_9f6ba 
      ld: can't map file, errno=22 file '/opt/homebrew/opt/ffmpeg@4/lib' for architecture arm64
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      make[1]: *** [cmTC_9f6ba] Error 1
      make: *** [cmTC_9f6ba/fast] Error 2

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:24 (project)

```

**Comment by ccbrown** [comment]
@lzuosym And idea why "/opt/homebrew/opt/ffmpeg@4/lib" might be getting added to that clang command? FFmpeg shouldn't have anything to do wit this. Do you have any environment variables set that could be impacting it? CFLAGS or LDFLAGS maybe?

**Comment by lzuosym** [comment]
After `brew install ffmpeg@4`, add the following complier flags according to the instructions. Without these settings,  `cargo run --bin cmd -- serve-http` would fail for `av-service`. 

```
set -gx LDFLAGS "-L/opt/homebrew/opt/llvm/lib /opt/homebrew/opt/ffmpeg@4/lib"
set -gx CPPFLAGS "-I/opt/homebrew/opt/llvm/include /opt/homebrew/opt/ffmpeg@4/include"
```

**Comment by lzuosym** [comment]
That's the issue. Working now! 👍 
Thanks!

**Pull request merged**
